//------------------------------------------------------------------------------
// <auto-generated>
// T4SSDT Data access layer code generator.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Data;

namespace Model
{
    [GeneratedCode("T4SSDT", "1.0")]
    public partial struct TypeMappingTestsTarget
    {
        public int Id { get; set; }
        public long? BigIntColumn { get; set; }
        public bool? BitColumn { get; set; }
        public decimal? DecimalColumn { get; set; }
        public short? SmallIntColumn { get; set; }
        public byte? TinyIntColumn { get; set; }
        public decimal? MoneyColumn { get; set; }
        public decimal? SmallMoneyColumn { get; set; }
        public double? FloatColumn { get; set; }
        public float? RealColumn { get; set; }
        public DateTime? DateColumn { get; set; }
        public DateTimeOffset? DateTimeOffsetColumn { get; set; }
        public DateTime? DateTime2Column { get; set; }
        public DateTime? SmallDateTimeColumn { get; set; }
        public DateTime? DateTimeColumn { get; set; }
        public TimeSpan? TimeColumn { get; set; }
        public string CharColumn { get; set; }
        public string NCharColumn { get; set; }
        public string VarcharColumn { get; set; }
        public string NVarcharColumn { get; set; }
        public byte[] BinaryColumn { get; set; }
        public byte[] VarbinaryColumn { get; set; }
        public string HierarchyidColumn { get; set; }
        public Guid? GuidColumn { get; set; }
        public string XmlColumn { get; set; }
    }

    [GeneratedCode("T4SSDT", "1.0")]
    public partial struct User
    {
        public short UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public byte[] HashedPassword { get; set; }
        public DateTime Created { get; set; }
    }

    [GeneratedCode("T4SSDT", "1.0")]
    public partial struct NullableColumnsView
    {
        public string UserName { get; set; }
        public short? RoleId { get; set; }
    }

    [GeneratedCode("T4SSDT", "1.0")]
    public partial struct UserRole
    {
        public string UserName { get; set; }
        public DateTime? Created { get; set; }
        public short? RoleId { get; set; }
    }

    [GeneratedCode("T4SSDT", "1.0")]
    public partial class TestTableType : DataTable
    {
        public TestTableType()
        {
            Columns.Add("Id", typeof(int?));
            Columns.Add("Name", typeof(string));
        }

        public void AddRow(
            int? id, 
            string name)
        {
            Rows.Add(
                id, 
                name);
        }
    }

}