//------------------------------------------------------------------------------
// <auto-generated>
// T4SSDT Data access layer code generator.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Data;

namespace Model
{
    [GeneratedCode("T4SSDT", "1.0")]
    public partial struct User
    {
        public short UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public byte[] HashedPassword { get; set; }
        public DateTime Created { get; set; }
    }

    [GeneratedCode("T4SSDT", "1.0")]
    public partial struct UserRole
    {
        public string UserName { get; set; }
        public DateTime Created { get; set; }
        public short RoleId { get; set; }
    }

    [GeneratedCode("T4SSDT", "1.0")]
    public partial class TestTableType : DataTable
    {
        public TestTableType()
        {
            Columns.Add("Id", typeof(int?));
            Columns.Add("Name", typeof(string));
        }

        public void AddRow(
            int? id, 
            string name)
        {
            Rows.Add(
                id, 
                name);
        }
    }

}