//------------------------------------------------------------------------------
// <auto-generated>
// T4SSDT Data access layer code generator.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.CodeDom.Compiler;

namespace Model
{
    [GeneratedCode("T4SSDT", "1.0")]
    public partial class User
    {
        public short UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public byte[] HashedPassword { get; set; }
        public DateTime Created { get; set; }
    }

    [GeneratedCode("T4SSDT", "1.0")]
    public partial class UserRole
    {
        public string UserName { get; set; }
        public DateTime Created { get; set; }
        public short RoleId { get; set; }
    }

}